name: Build/Deploy Azure Web App (Node/Express API)

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies & Compile
        run: |
          npm ci
          npm run build

      - name: Run Tests
        run: |
          npm run test --if-present

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production
      url: ${{ steps.DeployToAzureWebApp.outputs.webapp-url }}
    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./dist

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: LingoLinkAPI
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79D9D0D4BD7440286621DE2B4FFAFFC }}
          package: ./dist

      - name: Install Dependencies in Azure
        uses: azure/appservice-settings@v1
        with:
          app-settings-json: '[{"name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true", "slotSetting": false}, {"name": "npm start", "value": "node dist/app.js", "slotSetting": false}]'
          app-service-plan: 'ASP-worldchatgroup-9e75'
          web-app: 'LingoLinkAPI'