name: Build/Deploy Azure Web App (Node/Express API)

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: |
          npm run test --if-present

      - name: Prepare For Deployment
        run: |
          cp package.json ./dist
          cp package-lock.json ./dist

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist
          if-no-files-found: error

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production
      url: ${{ steps.DeployToAzureWebApp.outputs.webapp-url }}
    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: npm install

      - name: Log Current Directory Files
        run: |
          echo "Files And Folders In The Current Directory:"
          ls

      - name: Log Current Directory Name
        run: |
          echo "Name Of Current Directory:"
          pwd

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: LingoLinkAPI
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79D9D0D4BD7440286621DE2B4FFAFFC }}
          package: .

      - name: Log wwwroot Directory
        run: |
          az extension add --name webapp
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp log tail --name LingoLinkAPI --resource-group worldchat-group