name: Build/Deploy Azure Web App (Node/Express API)

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  BuildApplication:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: NPM Install, Build, Test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  DeployApplication:
    runs-on: ubuntu-latest
    needs: BuildApplication
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    environment:
      name: Production
      url: ${{ steps.DeployToAzureWebApp.outputs.webapp-url }}

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: LingoLinkAPI
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79D9D0D4BD7440286621DE2B4FFAFFC }}
          package: .