name: Build/Deploy Azure Web App (Node/Express API)

on:
  push:
    branches:
      - main

jobs:
  Build_application:
    if: github.event.head_commit.message != '' && contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'from') && contains(github.event.head_commit.message, 'dev')
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  deploy_application:
    if: github.event.head_commit.message != '' && contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'from') && contains(github.event.head_commit.message, 'dev')
    runs-on: ubuntu-latest
    needs: build_application
    environment:
      name: Production
      url: ${{ steps.DeployToAzureWebApp.outputs.webapp-url }}

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: LingoLinkAPI
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79D9D0D4BD7440286621DE2B4FFAFFC }}
          package: .